### ISSUE TITLE
remember login

### ISSUE THREAD

**Issue by rhiju** [vineetsk1/eternachat#1]
anyway to remember login/pass so that we don't have to retype? perhaps ios offers a way to store the info securely?

**Comment by rhiju** [comment]
whoa thanks @vineetsk1 
you had a TODO list in your presentation -- could you transfer those here as issues?
Then let's make an announcment in-game as a blog post with a link to these issues -- perhaps we can recruit new player devs to tackle them one by one

**Comment by vineetsk1** [comment]
Sounds good @rhiju - I just finished transferring them and have assigned a couple to me (I'll incrementally work through them in my free time) - for the ones that are currently unassigned that I'm hoping to finish for the next release (v3) I've assigned to the green 'help wanted' label. If I finish the ones I've assigned to me early then I can start work on those as well

I know LFP6 already offered to help with release v4 which will hopefully merge the html chat repo with this one, and make it so the app can be deployed to iOS and Android :)

Here's the link of issues for the next release for the blog post - https://github.com/EteRNAgame/eternachat/milestone/1

**Comment by rhiju** [comment]
wow merging with HTML5 for v4 :thumbsup:

that sounds like a major milestone -- at that point i bet we'll have sufficient experience with open-source development of eterna to be able to plan out an HTML5/ios buildout of the puzzle-solver applet.

**Comment by vineetsk1** [comment]
Feature implemented - closing thread (will be sent to Apple in next major release at August 15)
