### ISSUE TITLE
See full link

### ISSUE THREAD

**Issue by luxaritas** [vineetsk1/eternachat#11]
Currently, links just say "Link" with an underline. It would be nice to see the original text instead.

**Comment by vineetsk1** [comment]
Yeah initially I was showing original text but it was too long and was overflowing onto the edges of the screen. I realize now that I didn't really correct the problem, just introduced a new one 😛  

_Notes: The fix should remove the code that converts links to the text "Link" and should introduce code that allows for text-wrapping & a max-width of screen_
