### ISSUE TITLE
Use official username

### ISSUE THREAD

**Issue by vineetsk1** [vineetsk1/eternachat#3]
(Submitted by LFP6)

The app should not use the username typed in at login but the actual response from the server login

I'd prefer that the app used the capitalization that's recorded at Eterna (ie if I type lfp6 as my login, it should be LFP6 as it is officially on the server).

**Comment by vineetsk1** [comment]
Unfortunately the server login API call does not return the username, just the uid - implementing this will require 2 API calls to login the user (one to verify proper username/password credentials, and one to get the server-saved username with the correct casing).

**Comment by luxaritas** [comment]
That doesn't really surprise me, knowing how the website is built (a type=me call gets sent on every page afaik).

**Comment by vineetsk1** [comment]
Although it's a bit hacky, I've updated the login API call to immediately call the get user API call to also get the username - logging in now as **VineetBot** will correct to **vineetbot** :+1:
